### ISSUE TITLE
[Debate] 마커를 300개 이상 찍을 때 안드로이드 앱에서 부하가 생기는 이슈

### ISSUE THREAD

**Issue by dchecheb** [ko-salaam/ko-salaam-api#15]
다른 지도앱들을 봤더니 모든 마커를 다 표시하진 않음.
좋아요 수가 많은 장소, 혹은 랜덤으로 마커 개수를 제한해서 보여줌 
우리도 백엔드에서 아예 좋아요 순으로 sorting에서 개수 제한해서 보여주자.

### 구조
- DB에서 반경 nkm 이내 식당들을 다 꺼내온다.
- 300개 이상인지 체크한다.
- 현재 보고 있는 x, y 좌표 구간으로 4공간으로 나눈다,
- 공간별로 좋아요 순으로 75개씩 limit에서 다시 쿼리
- 합쳐서 응답

**Comment by dchecheb** [comment]
4구간으로 나눌 필요가 있나?? 고루 보여주려고 한 거긴 한데
일단 안나누고 거리순, 좋아요 순으로 sorting 해서 limit 300으로 보여줘 본 다음에
분산 잘안된다 싶으면 4구간으로 나누자.

**Comment by rhkrwngud445** [comment]
저도 조금 찾아봤는데 Fisher-Yates Shuffle 라는 알고리즘이 있더라구요! 데이터가 편향되지 않게 정렬하기 위한  뮤직 플레이어등에서 자주 사용하는 알고리즘 이라고 하는데, 도움되시지 않을까 싶어 남겨봅니다!
https://www.geeksforgeeks.org/shuffle-a-given-array-using-fisher-yates-shuffle-algorithm/

**Comment by dchecheb** [comment]
오 좋은 것 같아요. 적용 가능하겠는데요! 감사합니다 :D

**Comment by dchecheb** [comment]
https://daheenallwhite.github.io/programming/algorithm/2019/06/27/Shuffle-Algorithm-Fisher-Yates/
